spring.application.name=bankmanagement
server.port=8081
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=n
spring.datasource.url=jdbc:h2:file:./data/bankmanagement

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
